# -*- coding: utf-8 -*-
{
    'name': 'quotations',

    'summary': """
        Short (1 phrase/line) summary of the module's purpose, used as
        subtitle on modules listing or apps.openerp.com""",

    'description': """
        This module has been generated by Odoo Studio.
        It contains the apps created with Studio and the customizations of existing apps.
    """,
    
    'author': 'Felipe Navas ln@todoo.co',
    'website': "https://www.todoo.co/",
    
    'category': 'Uncategorized',
    'version': '1.0',    
    
    'depends': ['base'],

    'data': [
        'views/res_partner_view.xml',
    ],
    'installable': True,
}
